config/routes.rb
LocalWisdom::Application.routes.draw do
  get "role/list"
  get "role/show"
  get "role/submit"
  get "index/show"
  devise_for :users
  root :to => 'index#show'
  match 'role/submit' => 'role#submit', :via => :post

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role? :admin
        can :manage, :all
    else
        can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_and_belongs_to_many :roles

    def role?(role)
        return self.roles.find_by_name(role).try(:name) == role.to_s
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
    load_and_authorize_resource
  def list
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @role_items = Role.all
  end

  def submit
    user = User.find(params[:user_id])
    user.roles.clear
    if params[:role_checkbox]
        params[:role_checkbox].each do |item|
            role = Role.find(item)
            user.roles << role
        end
    end

    flash[:notice] = "User roles has been update"
    redirect_to controller: "role", action: "list"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocalWisdom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </p>

    <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>

</body>
</html>

app/views/role/list.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.email %></td>
                <td>
                    <% user.roles.each do |role| %>
                        <%= role.name %>&nbsp;
                    <% end %>
                </td>
                <td>
                    <%= link_to 'edit', role_show_path(id: user.id) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/role/show.html.erb
<h1><%= @user.email %></h1>
<div>
    <div>Set user role</div>
    <div class="set-role-block">
        <%= form_tag('/role/submit/', method: "post") do %>
            <%= hidden_field_tag :user_id, @user.id %>
            <ul>
                <% @role_items.each do |item| %>
                    <% if @user.roles.include? (item) %>
                        <li> <%= check_box_tag "role_checkbox[]", item.id, checked: true %> <%= item.name %> </li>
                    <% else %>
                        <li> <%= check_box_tag "role_checkbox[]", item.id %> <%= item.name %> </li>
                    <% end %>
                <% end %>
            </ul>
            <%= submit_tag "Update" %>
        <% end %>
    </div>

    <div class="link">
        <%= link_to 'back', role_list_path() %>
    </div>

</div>

app/views/role/submit.html.erb
<h1>Role#submit</h1>
<p>Find me in app/views/role/submit.html.erb</p>